# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      updateType:
        description: 'Update type'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - miner
        - patch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Update Version
        run: |
          pwd
          cd samples
          # ファイルからバージョンを読み取る
          version=$(cat VERSION)

          # バージョンをドットで分割して配列に格納する
          IFS='.' read -ra VERSION <<< "$version"

          # 引数によって対応するバージョン番号を増加させる
          case $TYPE in
            "major")
              ((VERSION[0]++))
              VERSION[1]=0
              VERSION[2]=0
              ;;
            "minor")
              ((VERSION[1]++))
              VERSION[2]=0
              ;;
            "patch")
              ((VERSION[2]++))
              ;;
            *)
              echo "Unknown argument: $1"
              echo "Please use one of the following arguments: major, minor, patch"
              exit 1
          esac
          
          # バージョンを更新してファイルに書き込む
          echo "${VERSION[0]}.${VERSION[1]}.${VERSION[2]}" > VERSION

      - name: Run a one-line script
        run: |
          echo "Update type: $TYPE"
          echo "TAG_NAME=$(cat samples/VERSION)" >> $GITHUB_ENV
        env:
          TYPE: ${{ inputs.updateType }}
          
      - name: Run a one-line script
        run: |
          echo "New Tag: $TAG_NAME"
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: sample/VERSION
          tag: $TAG_NAME
